# Generated by Django 6.1.1 on 2026-09-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_enrollment_course_courseprerequisite_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='committee',
            table='committee',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursematerial',
            table='course_material',
        ),
        migrations.AlterModelTable(
            name='courseprerequisite',
            table='course_prerequisite',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='departmentresearcharea',
            table='department_research_area',
        ),
        migrations.AlterModelTable(
            name='disciplinaryrecord',
            table='student_disciplinary_record',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='student_course',
        ),
        migrations.AlterModelTable(
            name='lecturer',
            table='lecturer',
        ),
        migrations.AlterModelTable(
            name='lecturercourse',
            table='lecturer_course',
        ),
        migrations.AlterModelTable(
            name='lecturerexpertise',
            table='lecturer_expertise',
        ),
        migrations.AlterModelTable(
            name='lecturerqualification',
            table='lecturer_qualification',
        ),
        migrations.AlterModelTable(
            name='lecturerresearchinterest',
            table='lecturer_research_interest',
        ),
        migrations.AlterModelTable(
            name='programme',
            table='programme',
        ),
        migrations.AlterModelTable(
            name='programmecourse',
            table='programme_course',
        ),
        migrations.AlterModelTable(
            name='projectfunding',
            table='project_funding',
        ),
        migrations.AlterModelTable(
            name='projectoutcome',
            table='project_outcome',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='publication',
        ),
        migrations.AlterModelTable(
            name='researchgroup',
            table='research_group',
        ),
        migrations.AlterModelTable(
            name='researchproject',
            table='project',
        ),
        migrations.AlterModelTable(
            name='society',
            table='society',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.CreateModel(
            name='LecturerCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.committee')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.lecturer')),
            ],
            options={
                'db_table': 'lecturer_committee',
            },
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='committees',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='lecturers', through='records.LecturerCommittee', to='records.committee'),
        ),
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.researchproject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
            options={
                'db_table': 'project_student',
            },
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='students',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='research_projects', through='records.ProjectStudent', to='records.student'),
        ),
        migrations.CreateModel(
            name='StudentSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.society')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
            options={
                'db_table': 'student_society',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='societies',
        ),
        migrations.AddField(
            model_name='student',
            name='societies',
            field=models.ManyToManyField(blank=True, related_name='students', through='records.StudentSociety', to='records.society'),
        ),
        migrations.AddConstraint(
            model_name='lecturercommittee',
            constraint=models.UniqueConstraint(fields=('lecturer', 'committee'), name='unique_lecturer_committee'),
        ),
        migrations.AddConstraint(
            model_name='projectstudent',
            constraint=models.UniqueConstraint(fields=('project', 'student'), name='unique_project_student'),
        ),
        migrations.AddConstraint(
            model_name='studentsociety',
            constraint=models.UniqueConstraint(fields=('student', 'society'), name='unique_student_society'),
        ),
    ]
